<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N7Z0SFY1" name="com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox" tests="5" failures="0" timestamp="23 Nov 2016 09:36:13 GMT" time="2.266" errors="1">
  <testcase name="pdfVerification" time="0.070" classname="com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox">
    <error type="java.lang.AssertionError" message="Failed to find content : NEGATIVE TEST in PDF, on Page Number : 2 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed to find content : NEGATIVE TEST in PDF, on Page Number : 2 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox.pdfVerification(PDFVerificationUsingPDFBox.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- pdfVerification -->
  <testcase name="pdfVerification" time="0.080" classname="com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox"/>
  <testcase name="pdfVerification" time="0.249" classname="com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox"/>
  <testcase name="pdfVerification" time="0.247" classname="com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox"/>
  <testcase name="pdfVerification" time="1.620" classname="com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox"/>
</testsuite> <!-- com.sqs.test.java.pdfVerification.PDFVerificationUsingPDFBox -->
